bc:
  _target_: bc_dataset.BCDataset
  env_name: ???
  name: bc_dataset
train:
  _target_: dataset.EpisodesDatasetRamMonitoring
  max_ram_usage: 30G
  name: train_dataset
test:
  _target_: dataset.EpisodesDataset
  max_num_episodes: null
  name: test_dataset
